# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Skye
#ShootingWang
subtitle: ''
description: '刻苦，沉着，精进不休' # 2021.04.28
#'无猫病重症患者'
#'统计一只狗，梦想有只猫'
keywords:
author: Skye
#ShootingWang
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://github.com/ShootingWang/ShootingWang.github.io
root: /
permalink:  :title.html
##:year/:month/:day/:title/
permalink_defaults:
#  urlname: index
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
#fluid
  # landscape

# index2 generator是否包含官方的hexo-generator-index，默认true（包含）
# index2 generator是否包含官方的hexo-generator-index，默认true（包含）
index2_include_index: true # defult is true

# 配置index2 generator，可以是数组或对象
index2_generator:
  per_page: 10
  order_by: -date
  include:
    - category Home # 只包含Web分类下的文章
  exclude:
    - tag Hide # 不包含标签为Hexo的文章



# Markdown-it config
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-checkbox
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-deflist
    ##- markdown-it imsize
    - markdown-it-mark
    - markdown-it-regexp
    - markdown-it-task-checkbox
    - name: markdown-it-container
      options: success
    - name: markdown-it-container
      options: info
    - name: markdown-it-container
      options: warning
    - name: markdown-it-container
      options: danger 
    - markdown-it-deflist
    - name: markdown-it-emoji
      options: 
        shortcuts: {}
  anchors:
    level: 1
    collisionSuffx: 'v'
    permalink: true
    permalinkClass: header-anchor
    permalinkSymbol: ''

## 锚点
marked:
  anchorAlias: true
  #gfm: true ## 复选框

## 搜索功能
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:shootingwang/shootingwang.github.io.git
  branch: master

toc:
  enable: true
  maxdepth: 6
  number: true
  class: toc
#  slugify: false
#  decodeEntities: false
#  anchor:
#    position: right
#    symbol: '#'
#    style: header-anchor

#heading_index:
#  enable: true
#  index_styles: "{1}{1}{1}{1}{1}{1}"
#  connector: "."
#  global_prefix: ""
#  global_suffix: ". "

highlight: # 代码高亮
  enable: true
  style: 'Vs 2015'  # 高亮样式见：https://highlightjs.org/static/demo/  在页面挑选 style 填入
  bg_color: false  # 是否根据 style 改变代码背景色，如果 style 是白色背景最好关闭此项
  copy_btn: true  # 是否开启复制代码的按钮
  auto_detect: true  # 自动检测
  line_number: false

#prism_plugin:
#  mode: 'preprocess'
#  theme: 'tomorrow'
#  line_number: false
#  custom_css:

mermaid:
  enable: true
  version: "7.1.2"

symbols_count_time:
  symbols: false  ## 文章字数统计
  time: false  ## 文章阅读时长
  total_symbols: true  ## 站点总字数
  total_time: true  ## 站点总阅读时长
  exclude_codeblock: true  ## 排除代码字数统计
